### ISSUE TITLE
运行decodetotextureOESActivity的时候出现下面这个错误，请问是什么原因

### ISSUE THREAD

**Issue by xiangxin99** [jiemojiemo/LearnMediaCodec#1]
11-27 11:14:08.268 17211 17211 E AndroidRuntime: FATAL EXCEPTION: main
11-27 11:14:08.268 17211 17211 E AndroidRuntime: Process: com.example.learnmediacodec, PID: 17211
11-27 11:14:08.268 17211 17211 E AndroidRuntime: java.lang.IllegalStateException: queueInputBuffer() is valid only at Executing states; currently at Uninitialized state
11-27 11:14:08.268 17211 17211 E AndroidRuntime: 
11-27 11:14:08.268 17211 17211 E AndroidRuntime:        at android.media.MediaCodec.native_queueInputBuffer(Native Method)
11-27 11:14:08.268 17211 17211 E AndroidRuntime:        at android.media.MediaCodec.queueInputBuffer(MediaCodec.java:2969)
11-27 11:14:08.268 17211 17211 E AndroidRuntime:        at com.example.learnmediacodec.DecodeToTextureOESActivity$decodeToSurfaceAsync$3.onInputBufferAvailable(DecodeToTextureOESActivity.kt:136)
11-27 11:14:08.268 17211 17211 E AndroidRuntime:        at android.media.MediaCodec$EventHandler.handleCallback(MediaCodec.java:1927)
11-27 11:14:08.268 17211 17211 E AndroidRuntime:        at android.media.MediaCodec$EventHandler.handleMessage(MediaCodec.java:1855)
11-27 11:14:08.268 17211 17211 E AndroidRuntime:        at android.os.Handler.dispatchMessage(Handler.java:107)
11-27 11:14:08.268 17211 17211 E AndroidRuntime:        at android.os.Looper.loopOnce(Looper.java:249)
11-27 11:14:08.268 17211 17211 E AndroidRuntime:        at android.os.Looper.loop(Looper.java:337)
11-27 11:14:08.268 17211 17211 E AndroidRuntime:        at android.app.ActivityThread.main(ActivityThread.java:9638)
11-27 11:14:08.268 17211 17211 E AndroidRuntime:        at java.lang.reflect.Method.invoke(Native Method)
11-27 11:14:08.268 17211 17211 E AndroidRuntime:        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:615)
11-27 11:14:08.268 17211 17211 E AndroidRuntime:        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:935)

**Comment by jiemojiemo** [comment]
不太确定，看起来是 codec configure 或者 start 失败，可以在代码里尝试捕获这两个方法的异常，看看是否成功。对应方法的文档：https://developer.android.google.cn/reference/android/media/MediaCodec#configure(android.media.MediaFormat,%20android.view.Surface,%20android.media.MediaCrypto,%20int)

**Comment by xiangxin99** [comment]
我看了下，还在解码的时候最下面把这个 mediacodec等信息给释放了，导致出现问题。删除了之后没有问题，可能需要在合适的时机进行释放资源和停止
